[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2
fuzz = { runs = 256, max_test_rejects = 65536 }

# Ethereum settings for deployment
[rpc_endpoints]
local = "http://localhost:8545"
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Local development settings

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
